// A folder of Markdown describing every entity, for an agent (or a person) to read.
//
// The JSON graph is built to be pasted whole into a prompt, so it stays lean. The
// docs are the opposite: one file per entity, as much detail as is useful (fill
// rates, distinct counts, ranges, picklist values, every relationship in and
// out), meant to be opened one entity at a time as a task needs it.
//
// Layout:
//
//     <dir>/README.md            start here: statistics, every entity, load order
//     <dir>/relationships.md     every relationship in one table
//     <dir>/entities/<Name>.md   one per entity
//
// Every file starts with Marker. A rerun deletes the marked files it no longer
// writes, so an entity that left the extract cannot leave a stale page behind,
// and nothing else in the folder is ever touched.

using System.Diagnostics;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace DepGraph;

/// <summary>Extract-level facts the graph does not carry, for the docs index.</summary>
public sealed record DocsContext
{
    public int? Files { get; init; }
    public long Bytes { get; init; }
    public int Archives { get; init; }
    public int Copies { get; init; }
    public int ExcludedEmpty { get; init; }
    public IReadOnlyList<string> Unreadable { get; init; } = [];
    public string Generated { get; init; } = DateTime.Today.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
}

public static partial class Docs
{
    public const string Marker = "<!-- generated by depgraph";

    /// <summary>Picklist values longer than this are cut short in tables.</summary>
    const int ValueWidth = 40;

    static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    // --- formatting ---------------------------------------------------------------

    static string N(long x) => Fmt.N(x);

    static string Pct(double x)
    {
        if (x is 0 or 1)
            return Fmt.Percent(x, 0);
        return x is >= 0.001 and <= 0.999 ? Fmt.Percent(x, 1) : Fmt.Percent(x, 2);
    }

    static string Bytes(long bytes)
    {
        double n = bytes;
        foreach (var unit in new[] { "B", "KB", "MB", "GB" })
        {
            if (n < 1024 || unit == "GB")
                return unit == "B" ? $"{n.ToString("N0", Inv)} {unit}" : $"{n.ToString("N1", Inv)} {unit}";
            n /= 1024;
        }
        throw new UnreachableException();
    }

    /// <summary>Make text safe inside a Markdown table cell.</summary>
    static string Cell(string text) => Whitespace().Replace(text, " ").Replace("|", "\\|").Trim();

    static string Code(string text)
    {
        text = Cell(text).Replace('`', '\'');
        return text.Length > 0 ? $"`{text}`" : "` `";
    }

    static string Value(object v)
    {
        switch (v)
        {
            case DateTime t:
                return t.TimeOfDay == TimeSpan.Zero
                    ? t.ToString("yyyy-MM-dd", Inv)
                    : t.ToString("yyyy-MM-dd HH:mm:ss", Inv);
            case double d:
                return Math.Abs(d) < 1e15
                    ? d.ToString("N2", Inv).TrimEnd('0').TrimEnd('.')
                    : d.ToString("0.##e+0", Inv);
            case long l:
                return N(l);
        }
        var text = Convert.ToString(v, Inv) ?? "";
        if (text.Length <= ValueWidth)
            return text;
        var cut = ValueWidth - 1;
        if (char.IsLowSurrogate(text[cut]))
            cut--; // do not split a character in two
        return text[..cut] + "…";
    }

    /// <summary>Entity id -> file name, unique even on a case-insensitive filesystem.</summary>
    static Dictionary<string, string> FileNames(IEnumerable<Node> nodes)
    {
        var output = new Dictionary<string, string>(StringComparer.Ordinal);
        var taken = new HashSet<string>(StringComparer.Ordinal);
        foreach (var n in nodes.OrderBy(n => n.Id, StringComparer.Ordinal))
        {
            var @base = Sources.Safe(n.Id);
            if (@base.Length == 0)
                @base = "entity";
            var (name, i) = (@base, 1);
            while (taken.Contains(name.ToLowerInvariant()))
                name = $"{@base}~{++i}";
            taken.Add(name.ToLowerInvariant());
            output[n.Id] = $"{name}.md";
        }
        return output;
    }

    static string Outside(string reason, string token)
    {
        var m = LooksLike().Match(reason);
        return $"{(m.Success ? m.Groups[1].Value : "prefix " + token)} (outside the extract)";
    }

    static string Resolves(Edge e) =>
        e.Kind == EdgeKind.NameOnly ? "0% (name-only guess)" : Pct(e.ResolveRate) + (e.Verified ? " verified" : "");

    sealed class Writer
    {
        readonly Graph g;
        readonly bool values;
        readonly DocsContext ctx;
        public readonly Dictionary<string, string> Files;
        readonly ILookup<string, Edge> outEdges;
        readonly ILookup<string, Edge> inEdges;
        readonly ILookup<string, Unresolved> unresolved;
        readonly Dictionary<string, int> layer = new(StringComparer.Ordinal);
        readonly Dictionary<string, List<string>> cycleOf = new(StringComparer.Ordinal);

        public Writer(Graph graph, bool values, DocsContext context)
        {
            g = graph;
            this.values = values;
            ctx = context;
            Files = FileNames(graph.Nodes);
            outEdges = graph.Edges.ToLookup(e => e.FromNode, StringComparer.Ordinal);
            inEdges = graph.Edges.ToLookup(e => e.ToNode, StringComparer.Ordinal);
            unresolved = graph.Unresolved.ToLookup(u => u.Node, StringComparer.Ordinal);
            for (var i = 0; i < graph.LoadOrder.Count; i++)
            {
                foreach (var n in graph.LoadOrder[i])
                    layer[n] = i + 1;
            }
            foreach (var c in graph.Cycles)
            {
                foreach (var n in c)
                    cycleOf[n] = c;
            }
        }

        string Link(string nodeId, bool fromEntities)
        {
            if (!Files.TryGetValue(nodeId, out var file))
                return Code(nodeId);
            var prefix = fromEntities ? "" : "entities/";
            return $"[{Cell(nodeId)}]({prefix}{file})";
        }

        List<string> Header(string what) =>
        [
            $"{Marker} {ToolVersion.Current} from {Cell(g.Source.Length > 0 ? g.Source : "an extract")} — "
            + $"{what}. Regenerate it rather than editing it. -->",
        ];

        // --- per-entity page -----------------------------------------------------

        public string Entity(Node n)
        {
            var output = Header($"entity {n.Id}");
            output.AddRange(
            [
                $"# {n.Id}",
                "",
                "[All entities](../README.md) · [All relationships](../relationships.md)",
                "",
            ]);
            var filled = n.Columns.Where(c => c.NonNull > 0).ToList();
            var empty = n.Columns.Where(c => c.NonNull == 0).ToList();
            var facts = new List<(string, string)>
            {
                ("Rows", N(n.Rows)),
                ("Columns", $"{n.Columns.Count} ({filled.Count} with data, {empty.Count} always empty)"),
            };
            if (n.Key is not null)
            {
                var key = $"`{n.Key}`";
                if (n.KeyToken is not null)
                    key += $", whose values start with the key prefix `{n.KeyToken}`";
                facts.Add(("Primary key", key));
            }
            else if (n.Columns.Count > 0)
            {
                facts.Add(("Primary key", "none found: no column is unique and non-empty"));
            }
            facts.Add(n.Parts.Count > 1
                ? ("Source", $"split across {n.Parts.Count} files ({Bytes(n.SizeBytes)}), merged into this one entity")
                : ("Source", $"{Code(n.Source)} ({Bytes(n.SizeBytes)})"));
            if (layer.TryGetValue(n.Id, out var nodeLayer))
            {
                var deps = outEdges[n.Id].Select(e => e.ToNode).Where(t => t != n.Id).Distinct()
                    .Order(StringComparer.Ordinal).ToList();
                var text = $"layer {nodeLayer} of {g.LoadOrder.Count}";
                text += deps.Count > 0
                    ? " — load after " + string.Join(", ", deps.Select(d => Link(d, true)))
                    : " — depends on nothing else in the extract";
                facts.Add(("Load order", text));
            }
            if (cycleOf.TryGetValue(n.Id, out var cycle))
            {
                var others = cycle.Where(x => x != n.Id).Select(x => Link(x, true));
                facts.Add(("Cycle", $"references itself circularly through {string.Join(", ", others)}; load them as one unit"));
            }
            var outgoing = outEdges[n.Id].ToList();
            var othersIn = inEdges[n.Id].Where(e => e.FromNode != n.Id).ToList();
            facts.Add(("Relationships",
                $"points at {outgoing.Select(e => e.ToNode).Distinct().Count()} entities through "
                + $"{outgoing.Select(e => e.FromColumn).Distinct().Count()} columns; referenced by "
                + $"{othersIn.Count} columns in {othersIn.Select(e => e.FromNode).Distinct().Count()} other entities"));
            output.AddRange(facts.Select(f => $"- **{f.Item1}:** {f.Item2}"));

            if (n.Parts.Count > 1)
            {
                output.AddRange(
                [
                    "",
                    "The export split this entity across several files. They are added "
                    + "together here: every count on this page covers all of them.",
                    "",
                    "| Part | Rows |",
                    "|---|---|",
                ]);
                for (var i = 0; i < n.Parts.Count; i++)
                    output.Add($"| {Code(n.Parts[i])} | {N(i < n.PartRows.Count ? n.PartRows[i] : 0)} |");
                output.Add($"| **Total** | **{N(n.Rows)}** |");
            }

            if (outgoing.Count > 0)
            {
                output.AddRange(
                [
                    "",
                    "## Points at",
                    "",
                    "Columns of this entity that hold references to other records.",
                    "",
                    "| Column | Target | Cardinality | Resolves | Empty | Notes |",
                    "|---|---|---|---|---|---|",
                ]);
                foreach (var e in outgoing.OrderBy(e => e.FromColumn, StringComparer.Ordinal).ThenBy(e => e.ToNode, StringComparer.Ordinal))
                {
                    var notes = new List<string>();
                    if (e.PolymorphicGroup is not null)
                    {
                        var others = outgoing
                            .Where(x => x.FromColumn == e.FromColumn && !ReferenceEquals(x, e))
                            .Select(x => x.ToNode)
                            .Order(StringComparer.Ordinal)
                            .Concat(unresolved[n.Id]
                                .Where(u => u.Column == e.FromColumn && u.Token is not null)
                                .Select(u => Outside(u.Reason, u.Token!)))
                            .ToList();
                        notes.Add("polymorphic" + (others.Count > 0 ? $", also points at {string.Join(", ", others)}" : ""));
                    }
                    if (e.Kind == EdgeKind.Self)
                        notes.Add("self-reference");
                    output.Add(
                        $"| `{Cell(e.FromColumn)}` | {Link(e.ToNode, true)}.`{Cell(e.ToColumn)}` | {e.Cardinality} | "
                        + $"{Resolves(e)} | {Pct(e.NullPct)} | {string.Join("; ", notes)} |");
                }
            }

            if (othersIn.Count > 0)
            {
                output.AddRange(
                [
                    "",
                    "## Referenced by",
                    "",
                    $"Columns in other entities that point at {n.Id}" + (n.Key is not null ? $".{n.Key}" : "") + ".",
                    "",
                    "| Entity | Column | Cardinality | Resolves |",
                    "|---|---|---|---|",
                ]);
                foreach (var e in othersIn.OrderBy(e => e.FromNode, StringComparer.Ordinal).ThenBy(e => e.FromColumn, StringComparer.Ordinal))
                    output.Add($"| {Link(e.FromNode, true)} | `{Cell(e.FromColumn)}` | {e.Cardinality} | {Resolves(e)} |");
            }

            if (unresolved[n.Id].Any())
            {
                output.AddRange(
                [
                    "",
                    "## References outside this extract",
                    "",
                    "These point at records that are not in the extract. That is not an "
                    + "error: the target object simply was not exported.",
                    "",
                    "| Column | Prefix | Rows | Why |",
                    "|---|---|---|---|",
                ]);
                foreach (var u in unresolved[n.Id].OrderBy(u => u.Column, StringComparer.Ordinal).ThenByDescending(u => u.Rows))
                    output.Add($"| `{Cell(u.Column)}` | {(u.Token is not null ? Code(u.Token) : "")} | {N(u.Rows)} | {Cell(u.Reason)} |");
            }

            if (filled.Count > 0)
            {
                output.AddRange(
                [
                    "",
                    "## Columns",
                    "",
                    "Filled is the share of rows with a value. Distinct counts different non-empty values."
                    + (values
                        ? $" Columns with at most {Ingest.TopValues} distinct values list them all, most common first, with row counts."
                        : ""),
                    "",
                    "| Column | Type | Filled | Distinct | Details |",
                    "|---|---|---|---|---|",
                ]);
                var refs = outgoing.ToLookup(e => e.FromColumn, StringComparer.Ordinal);
                foreach (var c in filled)
                {
                    var distinct = N(c.Distinct) + (c.Unique ? " (unique)" : "");
                    output.Add(
                        $"| `{Cell(c.Name)}` | {c.Type} | {Pct(c.NonNull / (double)c.Rows)} | {distinct} | "
                        + $"{Details(n, c, refs[c.Name].ToList())} |");
                }
            }

            if (empty.Count > 0)
            {
                output.AddRange(
                [
                    "",
                    $"## Always empty ({empty.Count})",
                    "",
                    "No row has a value in these columns.",
                    "",
                    string.Join(", ", empty.Select(c => $"`{Cell(c.Name)}`")),
                ]);
            }

            if (n.Warnings.Count > 0)
            {
                output.AddRange(["", "## Warnings", ""]);
                output.AddRange(n.Warnings.Select(w => $"- {Cell(w)}"));
            }
            return Join(output);
        }

        string Details(Node n, ColumnStats c, List<Edge> refs)
        {
            var bits = new List<string>();
            if (c.Name == n.Key)
                bits.Add("primary key");
            if (refs.Count > 0)
                bits.Add("references " + string.Join(", ", refs.OrderBy(e => e.ToNode, StringComparer.Ordinal).Select(e => Link(e.ToNode, true))));
            if (c.IdTokens.Count > 1 && c.Name != n.Key)
            {
                var total = Math.Max(c.IdTokens.Sum(t => t.Value), 1);
                bits.Add("prefixes " + string.Join(", ", c.IdTokens
                    .OrderByDescending(t => t.Value)
                    .Take(5)
                    .Select(t => $"`{t.Key}` {Pct(t.Value / (double)total)}")));
            }
            if (values && c.Min is not null && c.Max is not null)
                bits.Add(Equals(c.Min, c.Max) ? Value(c.Min) : $"{Value(c.Min)} to {Value(c.Max)}");
            if (values && c.TopValues is { Count: > 0 } top && c.Type != "id" && !(c.Unique && c.Distinct > 3))
            {
                var ranked = top.OrderByDescending(t => t.Value).ThenBy(t => t.Key, StringComparer.Ordinal);
                bits.Add(string.Join(" · ", ranked.Select(t => $"{Code(Value(t.Key))} {N(t.Value)}")));
            }
            if (c.MaxLength > 0 && c.Type is not ("id" or "date" or "datetime"))
                bits.Add($"up to {N(c.MaxLength.Value)} characters");
            return string.Join("; ", bits);
        }

        // --- index ---------------------------------------------------------------

        public string Readme()
        {
            var s = g.Stats;
            var cols = g.Nodes.SelectMany(n => n.Columns).ToList();
            var filled = cols.Count(c => c.NonNull > 0);
            var verified = g.Edges.Count(e => e.Verified);
            var split = g.Nodes.Where(n => n.Parts.Count > 1).ToList();
            var sourceName = g.Source.Length > 0 ? g.Source[(g.Source.LastIndexOfAny(['/', '\\']) + 1)..] : "extract";
            var output = Header("index");
            output.AddRange(
            [
                $"# Extract: {Cell(sourceName)}",
                "",
                $"Generated by depgraph {ToolVersion.Current} on {ctx.Generated} from {Code(g.Source)}, read with the `{g.Profile}` profile.",
                "",
                "## How to use these docs",
                "",
                "- Each entity (one table of the extract) has its own page in "
                + "`entities/`, listed below. A page gives the entity's size, primary key, "
                + "every column with fill rate, distinct count and range"
                + (values ? " or values" : "")
                + ", and every relationship in and out.",
                "- [relationships.md](relationships.md) lists every relationship in one table.",
                "- **Resolves** is the authority on whether a relationship is real: the "
                + "measured share of non-empty references found in the target's key. "
                + "*verified* means at least 90% resolve, so the relationship is proven "
                + "by the data. Below that it is real but some rows point at records "
                + "missing from the extract; *name-only* means nothing resolved and the "
                + "link is a guess from column names.",
                "- Entities whose files held no rows are not documented: an object "
                + "exported empty and an object not exported look the same here.",
                "",
                "## Statistics",
                "",
                "| | |",
                "|---|---|",
                $"| Entities | {N(g.Nodes.Count)} |",
                $"| Rows | {N(g.Nodes.Sum(n => n.Rows))} |",
                $"| Columns | {N(cols.Count)} ({N(filled)} with data, {N(cols.Count - filled)} always empty) |",
                $"| Relationships | {N(g.Edges.Count)} ({N(verified)} verified) |",
                $"| References outside the extract | {N(g.Unresolved.Count)} |",
            ]);
            if (ctx.Files is { } files)
            {
                var text = $"{N(files)} files, {Bytes(ctx.Bytes)}";
                if (ctx.Archives > 0)
                    text += $", in {N(ctx.Archives)} zip archive{(ctx.Archives != 1 ? "s" : "")}";
                output.Add($"| Source | {text} |");
            }
            if (split.Count > 0)
                output.Add($"| Split entities | {N(split.Count)}, merged from {N(split.Sum(n => n.Parts.Count))} files |");
            if (ctx.Copies > 0)
                output.Add($"| Identical copies skipped | {N(ctx.Copies)} |");
            if (ctx.ExcludedEmpty > 0)
                output.Add($"| Files with no rows, excluded | {N(ctx.ExcludedEmpty)} |");
            if (s?.Sampled == true)
                output.Add("| Sampled | yes: only the first rows of each file were read |");
            if (s is not null)
                output.Add($"| Build time | {s.TotalSeconds.ToString(Inv)} s |");

            output.AddRange(
            [
                "",
                "## Entities",
                "",
                "Points at and Referenced by count relationships, not rows.",
                "",
                "| Entity | Rows | Columns | Key | Points at | Referenced by | Layer |",
                "|---|---|---|---|---|---|---|",
            ]);
            foreach (var n in g.Nodes.OrderBy(n => n.Id.ToLowerInvariant(), StringComparer.Ordinal))
            {
                var key = n.Key is not null ? $"`{Cell(n.Key)}`" : "";
                if (n.KeyToken is not null)
                    key += $" ({n.KeyToken})";
                var inc = inEdges[n.Id].Count(e => e.FromNode != n.Id);
                output.Add(
                    $"| {Link(n.Id, false)} | {N(n.Rows)} | {n.Columns.Count(c => c.NonNull > 0)} of {n.Columns.Count} | "
                    + $"{key} | {outEdges[n.Id].Count()} | {inc} | {(layer.TryGetValue(n.Id, out var l) ? l.ToString(Inv) : "")} |");
            }

            if (g.Nodes.Count > 10)
            {
                output.AddRange(["", "## Largest entities", ""]);
                output.AddRange(g.Nodes.OrderByDescending(n => n.Rows).Take(10)
                    .Select((n, i) => $"{i + 1}. {Link(n.Id, false)}: {N(n.Rows)} rows"));
            }

            if (g.LoadOrder.Count > 0)
            {
                output.AddRange(
                [
                    "",
                    "## Load order",
                    "",
                    "Dependencies first: everything an entity points at is in an earlier layer, except inside a cycle.",
                    "",
                ]);
                for (var i = 0; i < g.LoadOrder.Count; i++)
                {
                    var layerNodes = g.LoadOrder[i];
                    var names = string.Join(", ", layerNodes.Select(x => Link(x, false)));
                    var cyc = layerNodes.Count > 1 && g.Cycles.Any(c => c.All(layerNodes.Contains));
                    output.Add($"{i + 1}. {names}" + (cyc ? " *(contains a cycle)*" : ""));
                }
            }

            if (g.Cycles.Count > 0)
            {
                output.AddRange(
                [
                    "",
                    "## Cycles",
                    "",
                    "These entities reference each other circularly and must be loaded "
                    + "as one unit, e.g. insert with the references empty, then update.",
                    "",
                ]);
                output.AddRange(g.Cycles.Select(c => "- " + string.Join(" ↔ ", c.Select(x => Link(x, false)))));
            }

            var problems = new List<string>();
            problems.AddRange(ctx.Unreadable.Select(label => $"Could not read {Code(label)}"));
            problems.AddRange((s?.UnmatchedIncludeNames ?? []).Select(name => $"Include list name {Code(name)} matched no file"));
            foreach (var n in g.Nodes)
                problems.AddRange(n.Warnings.Select(w => $"{Link(n.Id, false)}: {Cell(w)}"));
            if (problems.Count > 0)
            {
                output.AddRange(["", "## Warnings", ""]);
                output.AddRange(problems.Select(p => $"- {p}"));
            }
            return Join(output);
        }

        public string Relationships()
        {
            var output = Header("relationships");
            output.AddRange(
            [
                "# Relationships",
                "",
                "[All entities](README.md)",
                "",
                "Every reference column found, with how well its values resolve to the "
                + "target's key. *verified* means at least 90% resolve.",
                "",
                "| From | Column | To | Kind | Cardinality | Resolves | Empty |",
                "|---|---|---|---|---|---|---|",
            ]);
            var edges = g.Edges
                .OrderBy(e => e.FromNode, StringComparer.Ordinal)
                .ThenBy(e => e.FromColumn, StringComparer.Ordinal)
                .ThenBy(e => e.ToNode, StringComparer.Ordinal);
            foreach (var e in edges)
            {
                var kind = e.Kind + (e.PolymorphicGroup is not null ? ", polymorphic" : "");
                output.Add(
                    $"| {Link(e.FromNode, false)} | `{Cell(e.FromColumn)}` | {Link(e.ToNode, false)}.`{Cell(e.ToColumn)}` | "
                    + $"{kind} | {e.Cardinality} | {Resolves(e)} | {Pct(e.NullPct)} |");
            }
            if (g.Unresolved.Count > 0)
            {
                output.AddRange(
                [
                    "",
                    "## References outside the extract",
                    "",
                    "| From | Column | Prefix | Rows | Why |",
                    "|---|---|---|---|---|",
                ]);
                var outside = g.Unresolved
                    .OrderBy(u => u.Node, StringComparer.Ordinal)
                    .ThenBy(u => u.Column, StringComparer.Ordinal)
                    .ThenByDescending(u => u.Rows);
                foreach (var u in outside)
                    output.Add(
                        $"| {Link(u.Node, false)} | `{Cell(u.Column)}` | {(u.Token is not null ? Code(u.Token) : "")} | "
                        + $"{N(u.Rows)} | {Cell(u.Reason)} |");
            }
            return Join(output);
        }

        static string Join(List<string> lines) => string.Join("\n", lines) + "\n";
    }

    /// <summary>
    /// Write the docs folder and return the files written. <paramref name="values"/>
    /// false leaves out every data value (ranges and picklist values), keeping only
    /// structure and counts.
    /// </summary>
    public static List<string> Write(Graph graph, string outDir, bool values = true, DocsContext? context = null)
    {
        var docs = new Writer(graph, values, context ?? new DocsContext());
        var entities = Path.Combine(outDir, "entities");
        Directory.CreateDirectory(entities);

        var pages = new OrderedDictionary<string, string>(PathComparer)
        {
            [Path.GetFullPath(Path.Combine(outDir, "README.md"))] = docs.Readme(),
            [Path.GetFullPath(Path.Combine(outDir, "relationships.md"))] = docs.Relationships(),
        };
        foreach (var n in graph.Nodes)
            pages[Path.GetFullPath(Path.Combine(entities, docs.Files[n.Id]))] = docs.Entity(n);

        // Remove pages from an earlier run that this run does not rewrite, but only
        // ones this tool generated.
        var old = Directory.EnumerateFiles(outDir, "*.md").Concat(Directory.EnumerateFiles(entities, "*.md"));
        foreach (var path in old.Select(Path.GetFullPath).ToList())
        {
            if (!pages.ContainsKey(path) && Generated(path))
                File.Delete(path);
        }
        var utf8 = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
        foreach (var (path, text) in pages)
            File.WriteAllText(path, text, utf8);
        return pages.Keys.ToList();
    }

    static readonly StringComparer PathComparer = OperatingSystem.IsWindows() || OperatingSystem.IsMacOS()
        ? StringComparer.OrdinalIgnoreCase
        : StringComparer.Ordinal;

    static bool Generated(string path)
    {
        try
        {
            using var reader = new StreamReader(path, new UTF8Encoding(false, throwOnInvalidBytes: true));
            var head = new char[Marker.Length];
            return reader.ReadBlock(head) == Marker.Length && new string(head) == Marker;
        }
        catch (Exception exc) when (exc is IOException or UnauthorizedAccessException or DecoderFallbackException)
        {
            return false;
        }
    }

    [GeneratedRegex(@"\s+")]
    private static partial Regex Whitespace();

    [GeneratedRegex(@"looks like (\S+),")]
    private static partial Regex LooksLike();
}
