"""A folder of Markdown describing every entity, for an agent (or a person) to read.

The JSON graph is built to be pasted whole into a prompt, so it stays lean. The
docs are the opposite: one file per entity, as much detail as is useful (fill
rates, distinct counts, ranges, picklist values, every relationship in and
out), meant to be opened one entity at a time as a task needs it.

Layout::

    <dir>/README.md            start here: statistics, every entity, load order
    <dir>/relationships.md     every relationship in one table
    <dir>/entities/<Name>.md   one per entity

Every file starts with ``MARKER``. A rerun deletes the marked files it no
longer writes, so an entity that left the extract cannot leave a stale page
behind, and nothing else in the folder is ever touched.
"""

from __future__ import annotations

import datetime as dt
import re
from collections import defaultdict
from pathlib import Path

from . import __version__
from .ingest import TOP_VALUES
from .model import ColumnStats, Edge, Graph, Node

MARKER = "<!-- generated by depgraph"

#: Picklist values longer than this are cut short in tables.
_VALUE_WIDTH = 40


# --- formatting ---------------------------------------------------------------


def _n(x: int) -> str:
    return f"{x:,}"


def _pct(x: float) -> str:
    if x in (0, 1):
        return f"{x:.0%}"
    return f"{x:.1%}" if 0.001 <= x <= 0.999 else f"{x:.2%}"


def _bytes(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return f"{n:,.0f} {unit}" if unit == "B" else f"{n:,.1f} {unit}"
        n /= 1024
    return f"{n:,.1f} GB"


def _cell(text: str) -> str:
    """Make text safe inside a Markdown table cell."""
    return re.sub(r"\s+", " ", str(text)).replace("|", "\\|").strip()


def _code(text: str) -> str:
    text = _cell(text).replace("`", "'")
    return f"`{text}`" if text else "` `"


def _value(v) -> str:
    if isinstance(v, dt.datetime):
        if (v.hour, v.minute, v.second, v.microsecond) == (0, 0, 0, 0):
            return v.date().isoformat()
        return v.isoformat(sep=" ", timespec="seconds")
    if isinstance(v, float):
        return f"{v:,.2f}".rstrip("0").rstrip(".") if abs(v) < 1e15 else f"{v:.3g}"
    if isinstance(v, int) and not isinstance(v, bool):
        return _n(v)
    text = str(v)
    return text if len(text) <= _VALUE_WIDTH else text[: _VALUE_WIDTH - 1] + "…"


def _file_names(nodes: list[Node]) -> dict[str, str]:
    """Entity id -> file name, unique even on a case-insensitive filesystem."""
    out: dict[str, str] = {}
    taken: set[str] = set()
    for n in sorted(nodes, key=lambda n: n.id):
        base = re.sub(r"[^A-Za-z0-9._-]", "_", n.id) or "entity"
        name, i = base, 1
        while name.lower() in taken:
            i += 1
            name = f"{base}~{i}"
        taken.add(name.lower())
        out[n.id] = f"{name}.md"
    return out


class _Docs:
    def __init__(self, graph: Graph, values: bool, context: dict):
        self.g = graph
        self.values = values
        self.ctx = context
        self.files = _file_names(graph.nodes)
        self.out_edges: dict[str, list[Edge]] = defaultdict(list)
        self.in_edges: dict[str, list[Edge]] = defaultdict(list)
        for e in graph.edges:
            self.out_edges[e.from_node].append(e)
            self.in_edges[e.to_node].append(e)
        self.unresolved = defaultdict(list)
        for u in graph.unresolved:
            self.unresolved[u.node].append(u)
        self.layer = {n: i for i, layer in enumerate(graph.load_order, 1) for n in layer}
        self.cycle_of = {n: c for c in graph.cycles for n in c}

    def link(self, node_id: str, from_entities: bool) -> str:
        if node_id not in self.files:
            return _code(node_id)
        prefix = "" if from_entities else "entities/"
        return f"[{_cell(node_id)}]({prefix}{self.files[node_id]})"

    def header(self, what: str) -> list[str]:
        return [
            f"{MARKER} {__version__} from {_cell(self.g.source or 'an extract')} — "
            f"{what}. Regenerate it rather than editing it. -->",
        ]

    # --- per-entity page -----------------------------------------------------

    def entity(self, n: Node) -> str:
        out = self.header(f"entity {n.id}")
        out += [
            f"# {n.id}",
            "",
            "[All entities](../README.md) · [All relationships](../relationships.md)",
            "",
        ]
        filled = [c for c in n.columns if c.non_null]
        empty = [c for c in n.columns if not c.non_null]
        facts = [
            ("Rows", _n(n.rows)),
            (
                "Columns",
                f"{len(n.columns)} ({len(filled)} with data, {len(empty)} always empty)",
            ),
        ]
        if n.key:
            key = f"`{n.key}`"
            if n.key_token:
                key += f", whose values start with the key prefix `{n.key_token}`"
            facts.append(("Primary key", key))
        elif n.columns:
            facts.append(("Primary key", "none found: no column is unique and non-empty"))
        if len(n.parts) > 1:
            facts.append(
                (
                    "Source",
                    f"split across {len(n.parts)} files ({_bytes(n.size_bytes)}), "
                    "merged into this one entity",
                )
            )
        else:
            facts.append(("Source", f"{_code(n.source)} ({_bytes(n.size_bytes)})"))
        if n.id in self.layer:
            layer = self.layer[n.id]
            deps = sorted(
                {e.to_node for e in self.out_edges[n.id] if e.to_node != n.id}
            )
            text = f"layer {layer} of {len(self.g.load_order)}"
            text += (
                " — load after " + ", ".join(self.link(d, True) for d in deps)
                if deps
                else " — depends on nothing else in the extract"
            )
            facts.append(("Load order", text))
        if n.id in self.cycle_of:
            others = [x for x in self.cycle_of[n.id] if x != n.id]
            facts.append(
                (
                    "Cycle",
                    "references itself circularly through "
                    + ", ".join(self.link(x, True) for x in others)
                    + "; load them as one unit",
                )
            )
        outgoing = self.out_edges[n.id]
        others_in = [e for e in self.in_edges[n.id] if e.from_node != n.id]
        facts.append(
            (
                "Relationships",
                f"points at {len({e.to_node for e in outgoing})} entities through "
                f"{len({e.from_column for e in outgoing})} columns; referenced by "
                f"{len(others_in)} columns in "
                f"{len({e.from_node for e in others_in})} other entities",
            )
        )
        out += [f"- **{k}:** {v}" for k, v in facts]

        if len(n.parts) > 1:
            out += ["", "Parts:", ""] + [f"- {_code(p)}" for p in n.parts]

        if outgoing:
            out += [
                "",
                "## Points at",
                "",
                "Columns of this entity that hold references to other records.",
                "",
                "| Column | Target | Cardinality | Resolves | Empty | Notes |",
                "|---|---|---|---|---|---|",
            ]
            for e in sorted(outgoing, key=lambda e: (e.from_column, e.to_node)):
                notes = []
                if e.polymorphic_group:
                    others = sorted(
                        x.to_node
                        for x in outgoing
                        if x.from_column == e.from_column and x is not e
                    ) + [
                        _outside(u.reason, u.token)
                        for u in self.unresolved[n.id]
                        if u.column == e.from_column and u.token
                    ]
                    notes.append(
                        "polymorphic"
                        + (f", also points at {', '.join(others)}" if others else "")
                    )
                if e.kind == "self":
                    notes.append("self-reference")
                out.append(
                    f"| `{_cell(e.from_column)}` | {self.link(e.to_node, True)}"
                    f".`{_cell(e.to_column)}` | {e.cardinality} | {_resolves(e)} | "
                    f"{_pct(e.null_pct)} | {'; '.join(notes)} |"
                )

        if others_in:
            out += [
                "",
                "## Referenced by",
                "",
                f"Columns in other entities that point at {n.id}"
                + (f".{n.key}" if n.key else "")
                + ".",
                "",
                "| Entity | Column | Cardinality | Resolves |",
                "|---|---|---|---|",
            ]
            for e in sorted(others_in, key=lambda e: (e.from_node, e.from_column)):
                out.append(
                    f"| {self.link(e.from_node, True)} | `{_cell(e.from_column)}` | "
                    f"{e.cardinality} | {_resolves(e)} |"
                )

        if self.unresolved[n.id]:
            out += [
                "",
                "## References outside this extract",
                "",
                "These point at records that are not in the extract. That is not an "
                "error: the target object simply was not exported.",
                "",
                "| Column | Prefix | Rows | Why |",
                "|---|---|---|---|",
            ]
            for u in sorted(self.unresolved[n.id], key=lambda u: (u.column, -u.rows)):
                out.append(
                    f"| `{_cell(u.column)}` | {_code(u.token) if u.token else ''} | "
                    f"{_n(u.rows)} | {_cell(u.reason)} |"
                )

        if filled:
            out += [
                "",
                "## Columns",
                "",
                "Filled is the share of rows with a value. Distinct counts different "
                "non-empty values."
                + (
                    f" Columns with at most {TOP_VALUES} distinct values list them "
                    "all, most common first, with row counts."
                    if self.values
                    else ""
                ),
                "",
                "| Column | Type | Filled | Distinct | Details |",
                "|---|---|---|---|---|",
            ]
            refs: dict[str, list[Edge]] = defaultdict(list)
            for e in outgoing:
                refs[e.from_column].append(e)
            for c in filled:
                distinct = _n(c.distinct) + (" (unique)" if c.unique else "")
                out.append(
                    f"| `{_cell(c.name)}` | {c.dtype} | {_pct(c.non_null / c.rows)} | "
                    f"{distinct} | {self.details(n, c, refs.get(c.name, []))} |"
                )

        if empty:
            out += [
                "",
                f"## Always empty ({len(empty)})",
                "",
                "No row has a value in these columns.",
                "",
                ", ".join(f"`{_cell(c.name)}`" for c in empty),
            ]

        if n.warnings:
            out += ["", "## Warnings", ""] + [f"- {_cell(w)}" for w in n.warnings]
        return "\n".join(out) + "\n"

    def details(self, n: Node, c: ColumnStats, refs: list[Edge]) -> str:
        bits = []
        if c.name == n.key:
            bits.append("primary key")
        if refs:
            bits.append(
                "references "
                + ", ".join(
                    f"{self.link(e.to_node, True)}" for e in sorted(refs, key=lambda e: e.to_node)
                )
            )
        if c.id_tokens and c.name != n.key and len(c.id_tokens) > 1:
            total = sum(c.id_tokens.values()) or 1
            bits.append(
                "prefixes "
                + ", ".join(
                    f"`{t}` {_pct(k / total)}"
                    for t, k in sorted(c.id_tokens.items(), key=lambda t: -t[1])[:5]
                )
            )
        if self.values and c.min is not None and c.max is not None:
            bits.append(
                _value(c.min)
                if c.min == c.max
                else f"{_value(c.min)} to {_value(c.max)}"
            )
        if self.values and c.top_values and c.dtype != "id" and not (
            c.unique and c.distinct > 3
        ):
            ranked = sorted(c.top_values.items(), key=lambda t: (-t[1], t[0]))
            bits.append(" · ".join(f"{_code(_value(v))} {_n(k)}" for v, k in ranked))
        if c.max_length and c.dtype not in ("id", "date", "datetime"):
            bits.append(f"up to {_n(c.max_length)} characters")
        return "; ".join(bits)

    # --- index ---------------------------------------------------------------

    def readme(self) -> str:
        g, ctx = self.g, self.ctx
        s = g.stats
        cols = [c for n in g.nodes for c in n.columns]
        filled = sum(1 for c in cols if c.non_null)
        verified = sum(1 for e in g.edges if e.verified)
        split = [n for n in g.nodes if len(n.parts) > 1]
        out = self.header("index")
        out += [
            f"# Extract: {_cell(Path(g.source).name if g.source else 'extract')}",
            "",
            f"Generated by depgraph {__version__} on {ctx.get('generated', '')} "
            f"from {_code(g.source)}, read with the `{g.profile}` profile.",
            "",
            "## How to use these docs",
            "",
            "- Each entity (one table of the extract) has its own page in "
            "`entities/`, listed below. A page gives the entity's size, primary key, "
            "every column with fill rate, distinct count and range"
            + (" or values" if self.values else "")
            + ", and every relationship in and out.",
            "- [relationships.md](relationships.md) lists every relationship in one "
            "table.",
            "- **Resolves** is the authority on whether a relationship is real: the "
            "measured share of non-empty references found in the target's key. "
            "*verified* means at least 90% resolve, so the relationship is proven "
            "by the data. Below that it is real but some rows point at records "
            "missing from the extract; *name-only* means nothing resolved and the "
            "link is a guess from column names.",
            "- Entities whose files held no rows are not documented: an object "
            "exported empty and an object not exported look the same here.",
            "",
            "## Statistics",
            "",
            "| | |",
            "|---|---|",
            f"| Entities | {_n(len(g.nodes))} |",
            f"| Rows | {_n(sum(n.rows for n in g.nodes))} |",
            f"| Columns | {_n(len(cols))} ({_n(filled)} with data, "
            f"{_n(len(cols) - filled)} always empty) |",
            f"| Relationships | {_n(len(g.edges))} ({_n(verified)} verified) |",
            f"| References outside the extract | {_n(len(g.unresolved))} |",
        ]
        files = ctx.get("files")
        if files is not None:
            text = f"{_n(files)} files, {_bytes(ctx.get('bytes', 0))}"
            if ctx.get("archives"):
                k = ctx["archives"]
                text += f", in {_n(k)} zip archive{'s' if k != 1 else ''}"
            out.append(f"| Source | {text} |")
        if split:
            out.append(
                f"| Split entities | {_n(len(split))}, merged from "
                f"{_n(sum(len(n.parts) for n in split))} files |"
            )
        if ctx.get("copies"):
            out.append(f"| Identical copies skipped | {_n(ctx['copies'])} |")
        if ctx.get("excluded_empty"):
            out.append(f"| Files with no rows, excluded | {_n(ctx['excluded_empty'])} |")
        if s.get("sampled"):
            out.append("| Sampled | yes: only the first rows of each file were read |")
        if "total_seconds" in s:
            out.append(f"| Build time | {s['total_seconds']} s |")

        out += [
            "",
            "## Entities",
            "",
            "Points at and Referenced by count relationships, not rows.",
            "",
            "| Entity | Rows | Columns | Key | Points at | Referenced by | Layer |",
            "|---|---|---|---|---|---|---|",
        ]
        for n in sorted(g.nodes, key=lambda n: n.id.lower()):
            key = f"`{_cell(n.key)}`" if n.key else ""
            if n.key_token:
                key += f" ({n.key_token})"
            inc = [e for e in self.in_edges[n.id] if e.from_node != n.id]
            out.append(
                f"| {self.link(n.id, False)} | {_n(n.rows)} | "
                f"{sum(1 for c in n.columns if c.non_null)} of {len(n.columns)} | "
                f"{key} | {len(self.out_edges[n.id])} | {len(inc)} | "
                f"{self.layer.get(n.id, '')} |"
            )

        largest = sorted(g.nodes, key=lambda n: -n.rows)[:10]
        if len(g.nodes) > 10:
            out += ["", "## Largest entities", ""]
            out += [
                f"{i}. {self.link(n.id, False)}: {_n(n.rows)} rows"
                for i, n in enumerate(largest, 1)
            ]

        if g.load_order:
            out += [
                "",
                "## Load order",
                "",
                "Dependencies first: everything an entity points at is in an earlier "
                "layer, except inside a cycle.",
                "",
            ]
            for i, layer in enumerate(g.load_order, 1):
                names = ", ".join(self.link(x, False) for x in layer)
                cyc = any(set(c) <= set(layer) for c in g.cycles if len(layer) > 1)
                out.append(f"{i}. {names}" + (" *(contains a cycle)*" if cyc else ""))

        if g.cycles:
            out += [
                "",
                "## Cycles",
                "",
                "These entities reference each other circularly and must be loaded "
                "as one unit, e.g. insert with the references empty, then update.",
                "",
            ]
            out += [
                "- " + " ↔ ".join(self.link(x, False) for x in c) for c in g.cycles
            ]

        problems = []
        for label in ctx.get("unreadable", []):
            problems.append(f"Could not read {_code(label)}")
        for name in s.get("unmatched_include_names") or []:
            problems.append(f"Include list name {_code(name)} matched no file")
        for n in g.nodes:
            for w in n.warnings:
                problems.append(f"{self.link(n.id, False)}: {_cell(w)}")
        if problems:
            out += ["", "## Warnings", ""] + [f"- {p}" for p in problems]
        return "\n".join(out) + "\n"

    def relationships(self) -> str:
        g = self.g
        out = self.header("relationships")
        out += [
            "# Relationships",
            "",
            "[All entities](README.md)",
            "",
            "Every reference column found, with how well its values resolve to the "
            "target's key. *verified* means at least 90% resolve.",
            "",
            "| From | Column | To | Kind | Cardinality | Resolves | Empty |",
            "|---|---|---|---|---|---|---|",
        ]
        for e in sorted(g.edges, key=lambda e: (e.from_node, e.from_column, e.to_node)):
            kind = e.kind + (", polymorphic" if e.polymorphic_group else "")
            out.append(
                f"| {self.link(e.from_node, False)} | `{_cell(e.from_column)}` | "
                f"{self.link(e.to_node, False)}.`{_cell(e.to_column)}` | {kind} | "
                f"{e.cardinality} | {_resolves(e)} | {_pct(e.null_pct)} |"
            )
        if g.unresolved:
            out += [
                "",
                "## References outside the extract",
                "",
                "| From | Column | Prefix | Rows | Why |",
                "|---|---|---|---|---|",
            ]
            for u in sorted(g.unresolved, key=lambda u: (u.node, u.column, -u.rows)):
                out.append(
                    f"| {self.link(u.node, False)} | `{_cell(u.column)}` | "
                    f"{_code(u.token) if u.token else ''} | {_n(u.rows)} | "
                    f"{_cell(u.reason)} |"
                )
        return "\n".join(out) + "\n"


def _outside(reason: str, token: str) -> str:
    """'Lead (outside the extract)' from an unresolved reason, else the prefix."""
    m = re.search(r"looks like (\S+),", reason)
    return f"{m.group(1) if m else 'prefix ' + token} (outside the extract)"


def _resolves(e: Edge) -> str:
    if e.kind == "name-only":
        return "0% (name-only guess)"
    return _pct(e.resolve_rate) + (" verified" if e.verified else "")


def write_docs(
    graph: Graph, out_dir: Path, values: bool = True, context: dict | None = None
) -> list[Path]:
    """Write the docs folder and return the files written.

    ``values=False`` leaves out every data value (ranges and picklist values),
    keeping only structure and counts. ``context`` adds extract-level facts the
    graph does not carry: files, bytes, archives, copies, excluded_empty,
    unreadable, generated.
    """
    context = dict(context or {})
    context.setdefault("generated", dt.date.today().isoformat())
    docs = _Docs(graph, values, context)

    entities = out_dir / "entities"
    entities.mkdir(parents=True, exist_ok=True)
    pages = {out_dir / "README.md": docs.readme()}
    pages[out_dir / "relationships.md"] = docs.relationships()
    for n in graph.nodes:
        pages[entities / docs.files[n.id]] = docs.entity(n)

    # Remove pages from an earlier run that this run does not rewrite, but only
    # ones this tool generated.
    for old in [*out_dir.glob("*.md"), *entities.glob("*.md")]:
        if old not in pages and _generated(old):
            old.unlink()
    for path, text in pages.items():
        path.write_text(text, encoding="utf-8")
    return list(pages)


def _generated(path: Path) -> bool:
    try:
        with path.open(encoding="utf-8") as f:
            return f.read(len(MARKER)) == MARKER
    except (OSError, UnicodeDecodeError):
        return False
